###Auth
POST http://localhost:9000/auth/signup
Content-Type: application/json

{
    "username":"yohannes",
    "email":"yohannesalemayehu624@gmail.com",
    "password":"Yohannes624!",
    "role":"Admin"

}

###Auth
POST http://localhost:9000/auth/signup
Content-Type: application/json

{
    "username":"bereket",
    "email":"bereketKelay624@gmail.com",
    "password":"bereket624!",
    "role":"Admin"

}

###Auth
POST http://localhost:9000/auth/signup
Content-Type: application/json

{
    "username":"bekabir",
    "email":"bekaadmin765@gmail.com",
    "password":"bereket23!",
    "role":"Admin"

}
###Auth
POST http://localhost:9000/auth/signin
Content-Type: application/json

{
    "username":"yohannes",
    "password":"Yohannes624!"
}

###Auth
POST http://localhost:9000/auth/signin
Content-Type: application/json

{
    "username":"bereket",
    "password":"bereket624!"
}

### Auth
PATCH http://localhost:9000/auth/signout
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlvaGFubmVzYWxlbWF5ZWh1NjI0QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoieW9oYW5uZXMiLCJpYXQiOjE3MDUwNjk2ODQsImV4cCI6MTcwNzY2MTY4NH0.lvzjch-jkqv7Mu8MVMEyhJIM_jcT5qQTJk54Fx2-fkA

{
    "username":"yohannes",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlvaGFubmVzYWxlbWF5ZWh1NjI0QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoieW9oYW5uZXMiLCJpYXQiOjE3MDUwNzA3OTUsImV4cCI6MTcwNzY2Mjc5NX0.aX9iyl5eIzvORsyJUDYqJIfV8Pp9KpLKHNzNnTVuP70"

}

### Auth
PATCH http://localhost:9000/auth/signout
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDUwNzQzMjksImV4cCI6MTcwNzY2NjMyOX0.gTNc4oybVtJmqH2II2zCQJHBAFiAs4Axh90TjwZu8b0

{
    "username":"yohannes",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDUwNzQzMjksImV4cCI6MTcwNzY2NjMyOX0.gTNc4oybVtJmqH2II2zCQJHBAFiAs4Axh90TjwZu8b0"

}

###group
POST http://localhost:9000/groups
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDYzMDQzMzAsImV4cCI6MTcwODg5NjMzMH0.BJR2_bVEkLkr7xK9Iaf6V_MJqJHsFKBS1N0ZgIAVDuY

{
    "adminUsername": "bereket",
    "groupName": "votesphere5"
}

###groups
POST http://localhost:9000/groupmemberships
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDYzMDQzMzAsImV4cCI6MTcwODg5NjMzMH0.BJR2_bVEkLkr7xK9Iaf6V_MJqJHsFKBS1N0ZgIAVDuY

{
    "username":"yohannes"
}

###groups
POST http://localhost:9000/groupmemberships
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDYzMDQzMzAsImV4cCI6MTcwODg5NjMzMH0.BJR2_bVEkLkr7xK9Iaf6V_MJqJHsFKBS1N0ZgIAVDuY

{
    "username":"bekabir"
}

###groups
POST http://localhost:9000/groupmemberships
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDYzMDQzMzAsImV4cCI6MTcwODg5NjMzMH0.BJR2_bVEkLkr7xK9Iaf6V_MJqJHsFKBS1N0ZgIAVDuY

{
    "username":"yohannes"
}

###groups
DELETE http://localhost:9000/groupmemberships/yohannes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDYzMDQzMzAsImV4cCI6MTcwODg5NjMzMH0.BJR2_bVEkLkr7xK9Iaf6V_MJqJHsFKBS1N0ZgIAVDuY

###group
GET http://localhost:9000/groups/2/members
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDYzMDQzMzAsImV4cCI6MTcwODg5NjMzMH0.BJR2_bVEkLkr7xK9Iaf6V_MJqJHsFKBS1N0ZgIAVDuY

###poll
POST http://localhost:9000/polls
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDYzMDQzMzAsImV4cCI6MTcwODg5NjMzMH0.BJR2_bVEkLkr7xK9Iaf6V_MJqJHsFKBS1N0ZgIAVDuY

{
    "adminUsername":"bereket",
    "poll":{
        "question":"do you want series",
        "optionOne":"yes",
        "optionTwo":"no"
    }
}

###poll
GET http://localhost:9000/polls?groupId=2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDUwNzg5MDUsImV4cCI6MTcwNzY3MDkwNX0.vPbdzBGglZG9KGFZ59Os-KDT4YXab-VXpoomiOBgKeA

###poll
PATCH http://localhost:9000/polls/2/vote
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDUwNzg5MDUsImV4cCI6MTcwNzY3MDkwNX0.vPbdzBGglZG9KGFZ59Os-KDT4YXab-VXpoomiOBgKeA

{
    "username":"bereket",
    "optionId":"3"
}

###poll
DELETE http://localhost:9000/polls/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcmVrZXRLZWxheTYyNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlcmVrZXQiLCJpYXQiOjE3MDUwNzg5MDUsImV4cCI6MTcwNzY3MDkwNX0.vPbdzBGglZG9KGFZ59Os-KDT4YXab-VXpoomiOBgKeA